services:
  teslamate:
    image: teslamate/teslamate:2.0.0@sha256:e69b7155b8af81b0cdbcdc5e465292a9b8df5cf578bdb1d880666c9928dd7707
    restart: always
    environment:
      - ENCRYPTION_KEY=${TESLAMATE_ENCRYPTION_KEY:?}
      - DATABASE_USER=${POSTGRES_USER:?}
      - DATABASE_PASS=${POSTGRES_PASSWORD:?}
      - DATABASE_NAME=teslamate
      - DATABASE_HOST=database
      - MQTT_HOST=mosquitto
    ports:
      - "127.0.0.1:4000:4000"
    volumes:
      - ./import:/opt/app/import
    cap_drop:
      - all

  database:
    image: postgres:17.5-bookworm@sha256:864831322bf2520e7d03d899b01b542de6de9ece6fe29c89f19dc5e1d5568ccf
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER:?}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?}
      - POSTGRES_DB=teslamate
    volumes:
      - ./data/teslamate-db:/var/lib/postgresql/data

  grafana:
    image: teslamate/grafana:2.0@sha256:88bccf4a24514d2e26e53dcd0f944256afaf321cca19ef2b048514a87b1c2862
    restart: always
    environment:
      - DATABASE_USER=${POSTGRES_USER:?}
      - DATABASE_PASS=${POSTGRES_PASSWORD:?}
      - DATABASE_NAME=teslamate
      - DATABASE_HOST=database
    ports:
      - "127.0.0.1:3001:3000"
    volumes:
      - ./data/grafana:/var/lib/grafana

  mosquitto:
    image: eclipse-mosquitto:2.0.21@sha256:94f5a3d7deafa59fa3440d227ddad558f59d293c612138de841eec61bfa4d353
    restart: always
    command: mosquitto -c /mosquitto-no-auth.conf
    # ports:
    #   - "127.0.0.1:1883:1883"
    volumes:
      - ./data/mosquitto-conf:/mosquitto/config
      - ./data/mosquitto-data:/mosquitto/data


